### ISSUE TITLE
Testing: Translate the image text endpoint gives error

### ISSUE THREAD

**Issue by cbr-analytics** [PacktPublishing/Hands-On-Artificial-Intelligence-on-Amazon-Web-Services#1]
_Post method using command line curl to call the endpoint created in Chapter2, which call the recognition service and translate text service not working. Upon passing the below command with name of _my_s3_bucket_image_, I get error_

`curl --header "Content-Type: application/json" --request POST --data '{"fromLang":"auto","toLang":"en"}' http://127.0.0.1:8000/images/german-one-way-street-sign.jpg/translate-text`

> Error
`curl: (7) Failed to connect to 127.0.0.1 port 8000: Connection refused`

**Comment by csfalcon** [comment]
The above command is being issued to a local server at IP address 127.0.0.1 and port number 8000. The error is indicating that the local server is not reachable at that location.

Please make sure your local development environment is up and running with the command "chalice local", and check the command output for the IP address and port number the server is running on.
